export const movies = [
  {
    id: 1,
    title: 'The Dark Knight',
    genre: 'Action, Crime, Drama',
    director: 'Christopher Nolan',
    duration: '152 min',
    rating: 9.0,
    year: 2008,
    description: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
  },
  {
    id: 2,
    title: 'Inception',
    genre: 'Action, Sci-Fi, Thriller',
    director: 'Christopher Nolan',
    duration: '148 min',
    rating: 8.8,
    year: 2010,
    description: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
  },
  {
    id: 3,
    title: 'Interstellar',
    genre: 'Adventure, Drama, Sci-Fi',
    director: 'Christopher Nolan',
    duration: '169 min',
    rating: 8.6,
    year: 2014,
    description: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity survival.',
  },
  {
    id: 4,
    title: 'The Shawshank Redemption',
    genre: 'Drama',
    director: 'Frank Darabont',
    duration: '142 min',
    rating: 9.3,
    year: 1994,
    description: 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
  },
  {
    id: 5,
    title: 'Pulp Fiction',
    genre: 'Crime, Drama',
    director: 'Quentin Tarantino',
    duration: '154 min',
    rating: 8.9,
    year: 1994,
    description: 'The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.',
  },
];